[11.0][MIG] storage_backend
akretion/storage-deprecated-moved-to-oca pull request #41
Opened 2018-05-21 16:46 UTC by bodedra

2018-05-21 16:51 UTC, max3903 requested changes

2018-05-21 16:51 UTC, max3903 commented on oca_dependencies.txt
> +component https://github.com/OCA/connector 11.0
@bodedra Just put the repository name.

```
server-auth
connector
```

2018-05-21 18:34 UTC, max3903 commented
:+1:

2018-06-29 10:55 UTC, guewen commented
@sebastienbeau we are using this PR and #42 with success (not yet in production though)

2018-07-23 17:39 UTC, sebastienbeau commented
great news ! really have for the migration and to see other people using it ! I will review it this week !

2018-07-26 13:28 UTC, max3903 approved these changes

2019-04-10 10:29 UTC, florian-dacosta commented
@bodedra Thanks for the migration
I will close this as we are going to port the modules to version 12, and then backport it to towards version 11.

2019-04-10 10:29 UTC, closed without merging